* e-book
** e-book drm
Adobe Digital Editions installation using wine.
Working workaround:

https://appdb.winehq.org/objectManager.php?sClass=version&iId=33276

""" Begin quote

Selected Test Results

What works

Menu, authorization process, downloading files, viewing files

What does not

Installation out of the box, but has workaround

Workarounds

Install in a wine 32 prefix. Install the 4.5.0 version, since version 4.5.9 will not install giving an error "Adobe Digital Editions is already running". You laso need to install additional packages using winetricks and run a command to solve graphics glitch issue

1. Create clean wine32 prefix
WINEPREFIX="$HOME/.wine32" WINEARCH=win32 wine wineboot   

2. Install packages required for the installation
WINEPREFIX="$HOME/.wine32" winetricks corefonts dotnet40    

3. Download Adobe Digital Editions version 4.5.0 from https://filehippo.com/download...

4. Install it
WINEPREFIX="$HOME/.wine32" WINEARCH=win32 wine ADE_4.5_Installer.exe 

5. Fix graphics glitches
WINEPREFIX="$HOME/.wine32" winetricks ddr=gdi 

What was not tested

Everything else

Hardware tested

Graphics:

    GPU: Nvidia
    Driver: proprietary

Additional Comments

""" End of quote

use 'calibre' with DeDRM plugin to remove drm.

* usb

** Embedded libraries
- HID: http://www.signal11.us/oss/hidapi/

** USB IN A NUTSHELL

Taken from this excellent write-up at https://www.beyondlogic.org/usbnutshell/usb1.shtml.


*** Chapter 1

Brief overview off all chapters in the usb-standard and what you *really* need to read.
In short, the most important, and useful chapters of the usb-standard when designing peripheral devices are chapters (in addition to the material in the discussed guide):

- 2, Terms and Abbreviations
- 4, Architectural Overview
- 5, USB Data Flow Model (useful information, but a bit long)
- 7, Elecrical (only device speed identification is important)
- 8, Protocol Layer (only status reporting, and handshaking)
- 9, USB Device Frame Work (the most useful chapter, read in detail)


**** Topolgy
- One master -- called *host* in usb -- per network -- called *bus* in usb.
- OTG (On-The-Go), multiple entities on a single link can negotiate over who will be the host (eg. for mobile phone)
- 127 devices per bus.
- tiered star topology, use hubs to extend network

**** Data Link and Physical
- Serial bus
- 4 wires: +5V, GND, D+, D-
- D+ and D-, differential signaling pair
- NRZI (non-Return to zero) encoding
- synch field to synchronize host and reciever
 
**** Plug And Play
- hotplug
- host loads and unloads driver automatically
- PID/VID, Product ID, Vendor ID, used by host to determine correct driver.
- Pay USB Implementor's form to get PID and VID
- or search for existing suitable PID/VID for non-commercial projects.

**** Transfer modes
- Control
- Interrupt
- Bulk
- Isochronous, reserve bandwidth (eg. audio, video aplication)
